# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('date_of_birth', models.DateTimeField(verbose_name='DOB')),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
    ]
