# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
